name: Bazel Build and Test
on:
  push:
    branches: [ main ]
    paths:
        - Python/**
        - .github/**
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup bazelisk for Bazel builds
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Build Python Targets
        run: bazel build //Python/...
      - name: Run Tests
        run: bazel test //Python:split_test
  push-to-gcr:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v6
    - uses: docker/login-action@v4
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Push Images to GCR
      run: bazel run //Python:push_all
