name: Bazel Build and Test
on:
  push:
    branches: [ main ]
    paths:
        - Python/**
        - .github/**
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup bazelisk for Bazel builds
        # You may pin to the exact commit or the version.
        # uses: holvonix-open/setup-bazelisk@461095abb6f789e6093c2165080d0ce1db13f2ba
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Build Python Targets
        run: bazel build //Python/...
      - name: Run Tests
        run: bazel test //Python:split_test
